version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: interview-drills-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: upivot
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0
    container_name: interview-drills-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: interview-drills-api
    ports:
      - "4000:4000"
    volumes:
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json
      - ./api/tsconfig.json:/app/tsconfig.json
    working_dir: /app
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    # Load environment variables from the root .env file
    env_file:
      - .env
    environment:
      # These will be loaded from the .env file
      PORT: ${PORT:-4000}
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/upivot}
      JWT_SECRET: ${JWT_SECRET:-supersecret}
      SESSION_COOKIE_NAME: ${SESSION_COOKIE_NAME:-upivot_sid}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL:-http://localhost:4000/api/auth/google/callback}
      NODE_ENV: ${NODE_ENV:-development}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-300000}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: interview-drills-web
    ports:
      - "3000:3000"
    # Load environment variables from the root .env file
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:4000/api}
      VITE_GOOGLE_OAUTH_URL: ${VITE_GOOGLE_OAUTH_URL:-http://localhost:4000/api/auth/google}
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge